FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache

COPY .env .env
COPY gcp-credentials.json gcp-credentials.json
COPY ./app ./app
COPY ./templates ./templates

EXPOSE 8000

CMD ["/bin/bash", "-c", ".venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000"]
